FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000


# For production
# ----------------
# RUN npm run build

# RUN npm install -g serve

# CMD ["serve", "-s", "build", "-l", "3000"]
