FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir sqlalchemy psycopg2-binary pydantic

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]